### ISSUE TITLE
Creation of prior image

### ISSUE THREAD

**Issue by Aonnghus** [jabascal/ResPr-UNet-3D-Denoising-Efficient-Pipeline-TF-keras#1]
I am currently reading your paper on ResPr-UNet, but I don't quite understand how the prior images are calculated.
From what I understood, you compute 1 prior image per 2D slice from the noisy image using 10 slices wide stacks.
However, it is not said where $\tilde{u_i}$ is located inside the stack.

I would assume that $\tilde{u_i}$ is the middle slice, surrounded by 5 slices on both sides. But formula (2) does not seem to refer to this.

I looked for a code creating the prior images in the repo, but couldn't find any.

Could you help me on this matter?

**Comment by jabascal** [comment]
The prior is calculated using an exponentially weighted average of neighbor
slices on the noisy image. This leads to slightly blurred prior but with
increased SNR which guides the recovery. The results on the paper (metrics)
are computed on interior slices. However, we applied the entire volume. For
the case of slices on the top or bottom of the volume, one would have to
make a choice. We used less than 10 slices for these cases. For instance,
for the first slice, we did the weighted average of the five slices above
(weights can be easily computed from distances and then normalized for each
case).

As we couldn't release the paper data, the repository was created and
tested on a new dataset and has not been finalized yet. Sorry for this. It
could be done in the future if there is interest. Missing parts are the
SPADE method and prior computation, which were in Matlab and I was
reprogramming in Python, plus retraining and comparison on the new data.

I hope this helps.
Juan

**Comment by Aonnghus** [comment]
Thanks for your explanations.
However, I still don't understand how the neighbouring slices are chosen around $\tilde{u_i}$ for interior slices.
Does $j \in \left[i-\frac{M}{2}, i+\frac{M}{2}\right]$, i.e. stacks are centered on the noisy slice for which we want to compute the prior?

**Comment by jabascal** [comment]
Yes. To compute the prior, one can proceed one slice at a time, ie.
$u^p_i$ is computed from the volume $\tilde{u}$. Here, one could use
the entire volume $\tilde{u}$ where the further the slice $j$ from the
current slice $i$, the lower the weight. We used a truncated average,
so we only took 10 slices. In this case, each slice $u^p_i$ of the
volume is computed (as you said) from the neighboring slices, going
from $j=i-M/2$ to $j=i+M/2$.

**Comment by Aonnghus** [comment]
Thanks a lot!
